version: 1.0.{build}
image: Visual Studio 2015
environment:
  MYGET_SOURCE: https://www.myget.org/F/wcomab/
  MYGET_API_KEY:
    secure: MhkWny3UKd/FHtng/5lG59kxFgTW2YlKqVHYmshtYhteHXKymc92mK9mmPsrR6Yt
  SLACK_TOKEN:
    secure: uUlqYrJjlKpB0gfgUVR9NthjJi5bIt5je0h5UTq2uOuv0IoejZLmYsSvNYHw7ggy
build:
  verbosity: minimal
notifications:
- provider: Slack
  incoming_webhook:
    secure: se4ZgrGbFvolFWVA2tiWmNgJnnQpGGjExtCofl61u8mjPomk+wiDwkjaNOaltImU8TpfXtMr0PEuNjLmzr/d3fW4HQbBr6vwPAxn5L4elmI=
  channel: '#appveyor'
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
# Build script
build_script:
  - ps: .\build.ps1 -Target AppVeyor

# Tests
test: off